# Generated by Django 4.2.16 on 2024-09-29 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_category_slug_alter_product_price_and_more'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrderTime',
            new_name='OrderItem',
        ),
    ]
